version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies
      - chmod +x ./mvnw
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw clean install
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - target/**
