steps:
  # Step 1: Build the Spring Boot Application
  - name: 'gcr.io/cloud-builders/maven:3.6.3-jdk-11'
    id: 'Build Spring Boot Application'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests=true']

  # Step 2: Store the generated JAR file in Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Store Artifacts in Cloud Storage'
    args:
      - 'cp'
      - 'target/*.jar'
      - 'gs://bucket-mdso/springboot-artifacts/'

  # Step 3: Deploy the application to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'
      - '--quiet'
      - '--project=$iboncas-proyecto'

# Logging configuration (use Cloud Logging or Stackdriver)
options:
  logging: CLOUD_LOGGING_ONLY  # Log build results to Cloud Logging (Stackdriver)

# Timeout for Cloud Build process
timeout: 1200s
